version: '3.8'

services:
  django:
    image: python:3.10-slim-buster
    build:
      context: ./settings/django/
      dockerfile: Dockerfile
    volumes:
      - static:/static
      - ./settings/django/:/usr/src/app/:rw
    ports:
      - 8000:8000
    networks:
      - internal

  nginx:
    build: ./settings/nginx
    volumes:
      - static:/static
    ports:
      - "8080:80"
    depends_on:
      - django
    networks:
      - internal

networks:
  internal:
    name: internal


volumes:
  static:

